spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/la_juanita
spring.datasource.username=la_juanita
spring.datasource.password=la_juanita

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
